spring:
  profiles:
    active: dev_hjt  # 切换运行环境
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8     #查出来的 Date 时间与数据库中的时间相差 8 个小时
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB     #上传单个文件的最大值
      max-request-size: 10MB  #上传总文件的最大值
      resolve-lazily: false   # 是否延迟解析multipart请求
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #使用驼峰命名

##以下设置在生产环境中需要进行更改，确保唯一
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 259200 #JWT的超期限时间(60*60*24*3) 三天
  expirationRefreshToken: 54432000 #JWT的超期限时间(60*60*24*90*1000)
  tokenHead: Bearer #JWT负载中拿到开头
rsa:
  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALxNlYl5cKks93Fy8MqNajgtfAPOodrUyc/nWxKKsVBy4HBkCWq3MH7eB+MfNw3LXZrZBJ0cO/K2ijuKslcj1rc4fxALShWMvPOF2yb9GSZLLJ297nZJKuQu+FlGDj8NAr8R6dehWDMlgqcb8MqJwg7osdiB/Pshri5E4YHONu2VAgMBAAECgYB1dHN1J/HVJL5H3qlBvwnldsGnYkllRVuIukf9fdNyWeWTVWLmVNQEHpyO2BawHQ0LHJkbItRl5eS9lRr+7dTsql0VkFy8zXrDvUqzRys6NNa990G+umjWtpuGqucb322xI/HOHwQkraEix6xGG/1ts3tU6f9uEbVilqEfNbGKIQJBAPjP+5ymSjTdaEJP1CytppwDumA96sFaVhaIOKD0qVnKo7Lxts+QwKp+Ov0GoozQyzuseQXRDALkYYc/dSzdkQ0CQQDBvh9dDzZCc8rDmdlBfYg2klKnoaQCXBYi/rBgYMB80hBmzC2qKviNp8FaXpGrnzw+M55DbQ5hl7FMhHKzt9ypAkEAlRTpif8JT4uqQLFcTDjwL2L8dVYkJx5dnrqYU7jFEAwe8cVq6AuvpXhlF9613vHsFCFPknCjZcg5t7QKHYvUsQJBAIAOHwLOTCnOCQYSCTQtObwAKNudjh71KLiGqKN7L58Q5UBc0g34iwJuD/GgMh5CiHoAeinMykWdEtYlcP7ylskCQFjXZvTqwpHQuD6WgU55Qzp55K6lVEiM1hoZeeXpbtxlb1uf9yN+99g92e5o0jJwIgUCUPBA+evZRweTUO9ub6c=

## 以下操作用于获取用户的真实ip
server:
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
